const [GET_RECIPES, GET_RECIPE_BY_ID, GET_DIETS, GET_RECIPE_BY_NAME, SORT_AZ, SORT_ZA, FILTER_DIETS, FILTER_DATA_SOURCE, FILTER_HS, LOADING, CLEAR_DETAILS, DEFAULT] = [
  'GET_RECIPES',
  'GET_RECIPE_BY_ID',
  'GET_DIETS',
  'GET_RECIPE_BY_NAME',
  'SORT_AZ',
  'SORT_ZA',
  'FILTER_DIETS',
  'FILTER_DATA_SOURCE',
  'FILTER_HS',
  'LOADING',
  'CLEAR_DETAILS',
  'DEFAULT'
]

export { GET_RECIPES, GET_RECIPE_BY_ID, GET_DIETS, GET_RECIPE_BY_NAME, SORT_AZ, SORT_ZA, FILTER_DIETS, FILTER_DATA_SOURCE, FILTER_HS, LOADING, CLEAR_DETAILS, DEFAULT }